version: '3.9'

services:
  database:
    image: postgres:15.3-alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432

  maildev:
    restart: unless-stopped
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - ${ADMINER_PORT}:8080

  api:
    stdin_open: true
    tty: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - database
    links:
      - database
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}

volumes:
  db_data:
